name: News Crawler

on:
  schedule:
    - cron: '0 2 * * 1,4' # 02:00 UTC on Mon & Thu
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm --version
          node --version

      - name: Run crawler
        run: |
          node scripts/crawl-news.js

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(news): update markdown and index [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
