name: Scan Apartments

on:
  push:
    paths:
      - 'assets/imgs/Mặt bằng căn hộ/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run scanner
        run: node scripts/scan-apartments.js

      - name: Commit manifest
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(apartments): update sorted manifest [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
